[project]
name = "embedserv_wrapper"
version = "1.0.0"
description = "A wrapper for TPO-embedserv"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "requests"
]
[tool.setuptools]
packages = ["embedserv_wrapper"]
